### ISSUE TITLE
Axios Issues! 

### ISSUE THREAD

**Issue by rfos** [directus/sdk#126]
I'm having problems to use SDK with Next.JS 13.

It doesn't work if I follow the example from the repository: https://github.com/directus/examples/tree/main/nextjs

`    at Transport.request (/Users/rey/MAMP/www/reinaldoferro.com/tailwind-directus-blog/node_modules/@directus/sdk/dist/sdk.cjs.js:720:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Transport.get (/Users/rey/MAMP/www/reinaldoferro.com/tailwind-directus-blog/node_modules/@directus/sdk/dist/sdk.cjs.js:734:16)
    at async ItemsHandler.readByQuery (/Users/rey/MAMP/www/reinaldoferro.com/tailwind-directus-blog/node_modules/@directus/sdk/dist/sdk.cjs.js:64:32)
    at async getStaticProps (webpack-internal:///./src/pages/index.js:66:22)
    at async Object.renderToHTML (/Users/rey/MAMP/www/reinaldoferro.com/tailwind-directus-blog/node_modules/next/dist/server/render.js:389:20)
    at async doRender (/Users/rey/MAMP/www/reinaldoferro.com/tailwind-directus-blog/node_modules/next/dist/server/base-server.js:810:34)
    at async cacheEntry1.responseCache.get.incrementalCache.incrementalCache (/Users/rey/MAMP/www/reinaldoferro.com/tailwind-directus-blog/node_modules/next/dist/server/base-server.js:931:28)
    at async /Users/rey/MAMP/www/reinaldoferro.com/tailwind-directus-blog/node_modules/next/dist/server/response-cache/index.js:83:36 {
  parent: [AxiosError: Request failed with status code 404] {
    code: 'ERR_BAD_REQUEST',
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object],
      withCredentials: true,
      method: 'get',
      url: '/items/articles',
      params: [Object],
      data: undefined`

My .env file 
`DIRECTUS_URL=https://api.reinaldoferro.com
DIRECTUS_EMAIL=reinaldo.xxx@xxx.com
DIRECTUS_PASSWORD=PASSWORD HERE
`

Trying it from Postman it works.

**Comment by freekrai** [comment]
Are you on the latest SDK? I'm using the SDK with nextjs 13 and haven't seen this message.
