### ISSUE TITLE
Error "refresh_token" is required in either the JSON payload or Cookie"

### ISSUE THREAD

**Issue by BrunaFlor** [directus/sdk#141]
### Describe the Bug

I'm using directus SDK to manage login and logout of my users.
Unfortunatelly, when I log in through directus.auth.login() it don't create the refresh_token by default, and when I try to logout I get an error saing "refresh_token" is required in either the JSON payload or Cookie".
But even the function directus.auth.logout() don't receive any parameters. 

The same error happens when I try to use refresh().

### To Reproduce

import { Directus } from "@directus/sdk";

const directus = new Directus("https://mydirectusapi/");
export const login = async (user) => {
    try {
        const response = await directus.auth.login({
          email: user.email,
          password: user.password,
        });
        return response
      } catch (error) {
        console.error(error);
      }
}

export const LoggoutUser = async() => {
    try {
        const response = await directus.auth.logout();
        return response
      } catch (error) {
        console.error(error);
      }
}

### Directus Version

9.25.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
If you're relying on the `cookie` method make sure you correctly configure the cookie domain `REFRESH_TOKEN_COOKIE_DOMAIN` for your custom frontend https://docs.directus.io/self-hosted/config-options.html#security

**Comment by BrunaFlor** [comment]
> If you're relying on the `cookie` method make sure you correctly configure the cookie domain `REFRESH_TOKEN_COOKIE_DOMAIN` for your custom frontend https://docs.directus.io/self-hosted/config-options.html#security

I'm using this configuration, and still does not work. Is there any other possibility to fix this?

**Comment by co2nunes** [comment]
I also have this, also with `DIRECTUS_AUTH_REFRESH_TOKENS=true `
and `REFRESH_TOKEN_COOKIE_DOMAIN`

**Comment by andrew-frank** [comment]
I got the same exception, the regression happened just after upgrading the SDK from `10.3.1` to `10.3.3`.

Since the SDK upgrade, the `await directus.auth.refresh()` triggers an exception that cannot be handled / caught.

Stack trace:
```
TransportError: "refresh_token" is required in either the JSON payload or Cookie
    at Transport.request (.../node_modules/@directus/sdk/dist/sdk.cjs.js:720:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Transport.post (.../node_modules/@directus/sdk/dist/sdk.cjs.js:749:16)
    at async refreshPromise (.../node_modules/@directus/sdk/dist/sdk.cjs.js:855:30)```
```


To be specific, there are two exceptions. The first one is handled, program continues (it logs in with email and password), shortly after followed by the `refresh_token` exception that crashes the program.

Reproducible code from the docs, slightly modified:
```ts
export async function authenticate() {
  const client = await getDirectus()
  let authenticated = false

  try {
    throw new Error('If I throw here or comment out the whole block the program will work')
    await client.auth.refresh() // this throws twice (?)
    console.log('authenticated with token')
    authenticated = true
  } catch (_err) {}

  if (!authenticated) {
    const { ADMIN_EMAIL: email, ADMIN_PASSWORD: password } = process.env
    if (!email || !password) throw new Error('missing credential env vars')

    await client.auth
      .login({ email, password })
      .then(() => {
        console.log('authenticated with credentials') // this log is printed, followed by the error about `refresh_token`
        authenticated = true
      })
      .catch(err => {
        console.error(err)
        throw new Error('invalid credentials')
      })
  }

  return client.auth.token
}
```

**Comment by co2nunes** [comment]
Disabling redis cache to false apparently fixes removing the "cookie and the caches with the official JS SDK", though this is not the ideal setup for Production environment.

**Comment by andrew-frank** [comment]
There's no Redis set up in my scenario
