### ISSUE TITLE
Issue with build / bundler and rollup

### ISSUE THREAD

**Issue by claytongulick** [directus/sdk#26]
I'm using the @directus/sdk package as described in the docs:
import { Directus } from '@directus/sdk';

const directus = new Directus('');

But when doing a rollup build, I get:
[!] Error: 'default' is not exported by node_modules/axios/index.js, imported by node_modules/@directus/sdk/dist/sdk.bundler.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/@directus/sdk/dist/sdk.bundler.js (1:7)
1: import axios from 'axios';
          ^
2: 
3: class IAuth {
Error: 'default' is not exported by node_modules/axios/index.js, imported by node_modules/@directus/sdk/dist/sdk.bundler.js
    at error (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Module.error (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:12555:16)
    at Module.traceVariable (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:12914:29)
    at ModuleScope.findVariable (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:11566:39)
    at ChildScope.findVariable (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:6486:38)
    at ClassBodyScope.findVariable (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:6486:38)
    at ChildScope.findVariable (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:6486:38)
    at FunctionScope.findVariable (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:6486:38)
    at ChildScope.findVariable (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:6486:38)
    at MemberExpression.bind (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:8715:49)

The first line of sdk.bundler.js is:
import axios from 'axios';

But it looks like the axios build's index.js is CJS:
module.exports = require('./lib/axios');

So in order to make it work with rollup, a config like this is necessary:
```
plugins: [
      nodeResolve({ jsnext: true, preferBuiltins: true, browser: true }),
      json(),
      commonjs(),
]
```

There's a discussion about the issue here:
https://github.com/axios/axios/issues/1259

I'm not sure what the right solution is - Directus uses rollup by default, so I think most folks will roll with that when using it, but the docs as written don't work with it.

Is this a doc update thing? Or is there a different method of importing that should be used with browser build?

**Comment by rijkvanzanten** [comment]
That's a great question. What's the rollup config you're using? Is it the directus-extensions-sdk default?

The whole NodeJS CJS to ESM change has been a bit of a painful transition in the JS ecosystem. These odd quirks have been all too common unfortunately..

**Comment by claytongulick** [comment]
@rijkvanzanten this is all just vanilla, the component looks like:

```
import { Directus } from '@directus/sdk';

const directus = new Directus('');

class ComponentPatientScorecard extends HTMLElement {
...
}
```

and (working) rollup config looks like:
```
import { nodeResolve } from '@rollup/plugin-node-resolve';
import css from "rollup-plugin-import-css";
import json from '@rollup/plugin-json';
import commonjs from '@rollup/plugin-commonjs';

export default {
    input: 'src/index.js',
    output: {
      file: 'index.js',
      format: 'es',
      sourcemap: 'inline',
    },
    watch: {
        exclude: 'node_modules/**',
        skipWrite: false
    },
    plugins: [
      nodeResolve({ jsnext: true, preferBuiltins: true, browser: true }),
      json(),
      commonjs(),
      css()
    ]
  };
```

Took me a while to get there tho 😄

**Comment by rijkvanzanten** [comment]
> So in order to make it work with rollup, a config like this is necessary:

On second thought, this is actually pretty odd isn't it? As far as I understand, ESM _should_ be able to import from CJS sources out of the box, so assuming that rollup's ES support is regular node resolution based, that should work without any additional config 🤔 

@nickrum thoughts? 

(also fwiw, I've been meaning to refactor out `axios` of the SDK altogether to make it as lean as possible, but lets not get ahead of ourselves there and figure this out first). 

Also, @claytongulick fair to say this is more of a documentation problem than a bug in the platform? Seeing it's a custom rollup bundler configuration, it feels more like "Hey here's something you might want to know before getting started" instead of something we can resolve in the core codebase 🙂

**Comment by nickrum** [comment]
> On second thought, this is actually pretty odd isn't it? As far as I understand, ESM _should_ be able to import from CJS sources out of the box, so assuming that rollup's ES support is regular node resolution based, that should work without any additional config 🤔

The problem is that rollup doesn't understand CJS by default. That's why you have to use `@rollup/plugin-commonjs` which transpiles CJS to ESM before it's bundled by rollup. I would assume that's also where the error message @claytongulick was getting is coming from.

Definitely sounds like a documentation issue to me. Here is a minimal rollup config that will be able to bundle the sdk for the browser:

```js
import commonjs from '@rollup/plugin-commonjs';
import json from '@rollup/plugin-json';
import { nodeResolve } from '@rollup/plugin-node-resolve';

export default {
  input: 'src/index.js',
  output: {
    file: 'dist/index.js',
    format: 'es'
  },
  plugins: [nodeResolve({ browser: true }), commonjs(), json()]
};
```

**Comment by rijkvanzanten** [comment]
Linear: [ENG-74](https://linear.app/directus/issue/ENG-74/issue-with-build-bundler-and-rollup)

**Comment by ConnorSimply** [comment]
@rijkvanzanten Do you want me to make mention of this in the Docs or should we hold off until we replace Axios?

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten Do you want me to make mention of this in the Docs or should we hold off until we replace Axios?

To me the real fix for this is relying on natively available http connections rather than a third party lib, so let's hold off 👍🏻
