### ISSUE TITLE
Directus Nuxt plugin: users.me.read -> Maximum call stack size exceeded

### ISSUE THREAD

**Issue by 53rg0** [directus/sdk#53]
I use nuxt3 with directus and when access token expired but i refresh page i use fuction
```
onst user = await $directus.users.me.read({
          fields: ['*'],
        })
```

**But in console i got this**

```
Token found, fetching user from server
Exception in PromiseRejectCallback:
@directus/sdk:819
}
^

RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
@directus/sdk:923
await this._auth.refreshIfExpired();
^

RangeError: Maximum call stack size exceeded
Token is eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU0ZmRlYmJjLTdkZTYtNGY5Ni05N2ExLWZhNTdkNzk3YzVlNCIsInJvbGUiOiI0YTE2NWVlNS0wZDgzLTRjYjQtOGYwZC1hMjBmMGNkY2RjZjciLCJhcHBfYWNjZXNzIjoxLCJhZG1pbl9hY2Nlc3MiOjEsImlhdCI6MTY2MjkxMDY5OSwiZXhwIjoxNjYyOTEwNzU5LCJpc3MiOiJkaXJlY3R1cyJ9.WjAuMNQzJS1aE5Yg-UZ3Md7VKt9r1QQDADb1OymaCSc
TransportError: Maximum call stack size exceeded
at Transport.request (@directus/sdk:700:19)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Transport.get (@directus/sdk:704:16)
at async MeHandler.read (@directus/sdk:429:26)
at async Proxy.getUser (/Users/53rg0/Sites/TEST/store/auth.ts:55:22)
at async /Users/53rg0/Sites/TEST/plugins/directus.ts:39:85
at async Object.callAsync (file:///Users/53rg0/Sites/TEST/node_modules/unctx/dist/index.mjs:53:16)
at async applyPlugin (/Users/53rg0/Sites/TEST/node_modules/nuxt/dist/app/nuxt.mjs:74:23)
at async Module.applyPlugins (/Users/53rg0/Sites/TEST/node_modules/nuxt/dist/app/nuxt.mjs:84:5)
at async createNuxtAppServer (/Users/53rg0/Sites/TEST/node_modules/nuxt/dist/app/entry.mjs:30:7) {
  parent: TransportError: Maximum call stack size exceeded
  at Transport.request (@directus/sdk:700:19)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Transport.post (@directus/sdk:719:16)
  at async refreshPromise (@directus/sdk:825:30)
  at async Auth.refreshIfExpired (@directus/sdk:814:13)
  at async Transport.beforeRequest (@directus/sdk:923:21)
  at async Transport.request (@directus/sdk:668:22)
  at async Transport.get (@directus/sdk:704:16)
  at async MeHandler.read (@directus/sdk:429:26)
  at async Proxy.getUser (/Users/53rg0/Sites/TEST/store/auth.ts:55:22) {
    parent: TransportError: Maximum call stack size exceeded
    at Transport.request (@directus/sdk:700:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Transport.post (@directus/sdk:719:16)
    at async refreshPromise (@directus/sdk:825:30)
    at async Auth.refreshIfExpired (@directus/sdk:814:13)
    at async Transport.beforeRequest (@directus/sdk:923:21)
    at async Transport.request (@directus/sdk:668:22)
    at async Transport.post (@directus/sdk:719:16)
    at async refreshPromise (@directus/sdk:825:30)
    at async Auth.refreshIfExpired (@directus/sdk:814:13) {
      parent: [TransportError],
        response: undefined,
        errors: []
    },
    response: undefined,
      errors: []
  },
  response: undefined,
    errors: []
}

ERROR  [h3] [unhandled] Parse Error: Header overflow                                                                                                             19:14:10

at Socket.socketOnData (node:_http_client:521:22)
at Socket.emit (node:events:513:28)
at Socket.emit (node:domain:489:12)
at addChunk (node:internal/streams/readable:324:12)
at readableAddChunk (node:internal/streams/readable:297:9)
at Readable.push (node:internal/streams/readable:234:10)
at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

```

All other functions like login etc works fine like
```
const response = await $directus.auth.login({
          email,
          password,
        })

        // If login was successful, fetch the users data
        const user = await $directus.users.me.read({
          fields: ['*'],
        })
```

Prombem just when token shold be refreshed, code like 
`const refresh = await $directus.auth.refresh()`
**returns the same**
```
Token found, fetching user from server
Exception in PromiseRejectCallback:
@directus/sdk:819
    }
    ^

RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
@directus/sdk:923
                    await this._auth.refreshIfExpired();
                                     ^

```

**Comment by 53rg0** [comment]
Looks like loop somewhere here

```js
this._transport = new Transport({
				url: this.url,
				beforeRequest: async (config) => {
					await this._auth.refreshIfExpired();
					const token = this.storage.auth_token;
					const bearer = token
						? token.startsWith(`Bearer `)
							? String(this.storage.auth_token)
							: `Bearer ${this.storage.auth_token}`
						: '';

					return {
						...config,
						headers: {
							Authorization: bearer,
							...config.headers,
						},
					};
				},
				...this._options?.transport,
			});
```

**Comment by azrikahar** [comment]
This error piques my interest:

```
ERROR  [h3] [unhandled] Parse Error: Header overflow 
```

and h3 is a minimal Node http framework: https://github.com/unjs/h3, whereas there has been reports of Node http limiting the header size to 8kb as seen in:

- https://github.com/postmanlabs/postman-app-support/issues/8656
- https://stackoverflow.com/questions/64210829/how-to-set-maxheadersize-on-nuxtjs

The second link above feels particularly relevant here. Can you try doing adding the `NODE_OPTIONS='--max-http-header-size=16384'` when starting your Nuxt app?

**Comment by 53rg0** [comment]
The same...

Error H3 does not appear immediately, but after a long time in the console hangs below
```console
Token found, fetching user from server
Exception in PromiseRejectCallback:
@directus/sdk:819
    }
    ^

RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
@directus/sdk:923
                    await this._auth.refreshIfExpired();
                                     ^

RangeError: Maximum call stack size exceeded
Token is eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU0ZmRlYmJjLTdkZTYtNGY5Ni05N2ExLWZhNTdkNzk3YzVlNCIsInJvbGUiOiI0YTE2NWVlNS0wZDgzLTRjYjQtOGYwZC1hMjBmMGNkY2RjZjciLCJhcHBfYWNjZXNzIjoxLCJhZG1pbl9hY2Nlc3MiOjEsImlhdCI6MTY2MjkyOTMyNCwiZXhwIjoxNjYyOTI5Mzg0LCJpc3MiOiJkaXJlY3R1cyJ9.ME3TcFa-LG27UFVLpfzTVifGs2oSatBJ7_1uy6tF_9Y
TransportError: Maximum call stack size exceeded
    at Transport.request (@directus/sdk:700:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Transport.get (@directus/sdk:704:16)
    at async MeHandler.read (@directus/sdk:429:26)
    at async Proxy.getUser (/Users/53rg0/Sites/PODOLCHAK/store/auth.ts:55:22)
    at async /Users/53rg0/Sites/PODOLCHAK/plugins/directus.ts:39:85
    at async Object.callAsync (file:///Users/53rg0/Sites/PODOLCHAK/node_modules/unctx/dist/index.mjs:53:16)
    at async applyPlugin (/Users/53rg0/Sites/PODOLCHAK/node_modules/nuxt/dist/app/nuxt.mjs:74:23)
    at async Module.applyPlugins (/Users/53rg0/Sites/PODOLCHAK/node_modules/nuxt/dist/app/nuxt.mjs:84:5)
    at async createNuxtAppServer (/Users/53rg0/Sites/PODOLCHAK/node_modules/nuxt/dist/app/entry.mjs:30:7) {
  parent: TransportError: Maximum call stack size exceeded
      at Transport.request (@directus/sdk:700:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Transport.post (@directus/sdk:719:16)
      at async refreshPromise (@directus/sdk:825:30)
      at async Auth.refreshIfExpired (@directus/sdk:814:13)
      at async Transport.beforeRequest (@directus/sdk:923:21)
      at async Transport.request (@directus/sdk:668:22)
      at async Transport.get (@directus/sdk:704:16)
      at async MeHandler.read (@directus/sdk:429:26)
      at async Proxy.getUser (/Users/53rg0/Sites/PODOLCHAK/store/auth.ts:55:22) {
    parent: TransportError: Maximum call stack size exceeded
        at Transport.request (@directus/sdk:700:19)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Transport.post (@directus/sdk:719:16)
        at async refreshPromise (@directus/sdk:825:30)
        at async Auth.refreshIfExpired (@directus/sdk:814:13)
        at async Transport.beforeRequest (@directus/sdk:923:21)
        at async Transport.request (@directus/sdk:668:22)
        at async Transport.post (@directus/sdk:719:16)
        at async refreshPromise (@directus/sdk:825:30)
        at async Auth.refreshIfExpired (@directus/sdk:814:13) {
      parent: [TransportError],
      response: undefined,
      errors: []
    },
    response: undefined,
    errors: []
  },
  response: undefined,
  errors: []
}
```

**Comment by 53rg0** [comment]
When i delete  await this._auth.refreshIfExpired(); from SDK and compile i got 

```
TransportError: Token expired.
    at Transport.request (@directus/sdk:690:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Transport.get (@directus/sdk:704:16)
    at async MeHandler.read (@directus/sdk:429:26)
```

But fatal error with server 500 gone  but its not a solution :)

**Comment by 53rg0** [comment]
https://github.com/53rg0/directus-nuxt

Just change .env path to directus server and form fast problem detection i set ACCESS_TOKEN_TTL="1m"
Just after that login and close tab for 1 min and after try to load page - console will show you the same problem)

**Comment by 53rg0** [comment]
@bryantgillespie
Its seems like function await this._auth.refreshIfExpired(); runs anyway when session expired and not depends on auth method (I'm not sure that this line affects something. When I just remove it - nothing changes)

**Comment by 53rg0** [comment]
@rijkvanzanten, look at this please :)

**Comment by azrikahar** [comment]
This turned out to be super tricky, but the reason why it's looping is because of the custom storage class as @bryantgillespie suspected!

This is because even when the SDK tries to `resetStorage()` over here:

https://github.com/directus/sdk/blob/7a2462acabc6941bc2100c64627687f73f92de1a/src/base/auth.ts#L109-L117

and it sets all of the custom storage values to null over here:

https://github.com/directus/sdk/blob/7a2462acabc6941bc2100c64627687f73f92de1a/src/base/auth.ts#L68-L73

since we are using Nuxt useCookie, the `get()` in CookieStorage:

```js
  class CookieStorage extends BaseStorage {
    get(key) {
      const cookie = useCookie(key)
      return cookie.value
    }
    set(key, value) {
      const cookie = useCookie(key)
      return (cookie.value = value)
    }
    delete(key) {
      const cookie = useCookie(key)
      return (cookie.value = null)
    }
  }
```

will _still_ return the old value, because we can't just invalidate cookies _server side_ that way as that's not cookies are meant to work. Since it perpetually never gets "reset", it goes into an endless loop.

@bryantgillespie @53rg0 would you guys mind testing the following custom `CookieStorage` and replace the existing one in your nuxt directus plugin and let me know how it goes? There might be a cleaner approach, but this is a quick solution on "invalidating" the cookies _server side_, where we keep track of keys that are "reset"/deleted and prevent it from returning the stale value:

```js
  class CookieStorage extends BaseStorage {
    deletedKeys = new Set<string>()
    get(key) {
      if(this.deletedKeys.has(key)) return null;
      const cookie = useCookie(key)
      return cookie.value
    }
    set(key, value) {
      this.deletedKeys.delete(key)
      const cookie = useCookie(key)
      return (cookie.value = value)
    }
    delete(key) {
      this.deletedKeys.add(key)
      const cookie = useCookie(key)
      return (cookie.value = null)
    }
  }
```

**Comment by bryantgillespie** [comment]
Ahh - figured that was the case. Was using Nuxt > useCookie to try to keep the code as simple as possible but I didn't even consider that not playing nice with the SDK.

Thanks for the solution here @azrikahar . I'll test this out and get it added to my Nuxt starter.

**Comment by azrikahar** [comment]
> Ahh - figured that was the case. Was using Nuxt > useCookie to try to keep the code as simple as possible but I didn't even consider that not playing nice with the SDK.

From what I recall, `refreshIfExpired()` was actually a fairly recent addition which was prompted from another use case and/or specific race condition, so your code were actually working fine before it! 😄 It just happens to be a somewhat not-so-obvious quirk in terms of "getting" the cookie value even when it's expected to have been reset. 

Hopefully now it'll work well 🤞 it seems to refresh nicely from my brief tests, but would definitely love more sanity checks from you and other users. Thanks again for creating the plugin!

**Comment by 53rg0** [comment]
When i replace i got

```console
TransportError: Token expired.
    at Transport.request (@directus/sdk:690:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Transport.get (@directus/sdk:704:16)
    at async MeHandler.read (@directus/sdk:429:26)
```
AND

 ```console
parent: [AxiosError: Request failed with status code 401] {
    code: 'ERR_BAD_REQUEST',
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object],
      baseURL: 'http://0.0.0.0:8055',
      withCredentials: true,
      method: 'get',
      url: '/users/me',
      params: [Object],
      data: undefined
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /users/me?fields[]=* HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU0ZmRlYmJjLTdkZTYtNGY5Ni05N2ExLWZhNTdkNzk3YzVlNCIsInJvbGUiOiI0YTE2NWVlNS0wZDgzLTRjYjQtOGYwZC1hMjBmMGNkY2RjZjciLCJhcHBfYWNjZXNzIjoxLCJhZG1pbl9hY2Nlc3MiOjEsImlhdCI6MTY2MzA2NzExMiwiZXhwIjoxNjYzMDY3MTcyLCJpc3MiOiJkaXJlY3R1cyJ9.AxXnXW17JgPLLb11FhfWUKZjYAwcaMaG5NNeR1YdPuM\r\n' +
        'User-Agent: axios/0.27.2\r\n' +
        'Host: 0.0.0.0:8055\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/users/me?fields[]=*',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '0.0.0.0',
      protocol: 'http:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    response: {
      status: 401,
      statusText: 'Unauthorized',
      headers: [Object],
      config: [Object],
      request: [ClientRequest],
      data: [Object]
    }
  },
  response: {
    raw: { errors: [Array] },
    status: 401,
    statusText: 'Unauthorized',
    headers: {
      'content-security-policy': "script-src 'self' 'unsafe-eval';worker-src 'self' blob:;child-src 'self' blob:;img-src 'self' data: blob: https://cdn.directus.io;media-src 'self' https://cdn.directus.io;connect-src 'self' https://*;default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'",
      'x-powered-by': 'Directus',
      vary: 'Origin',
      'access-control-allow-credentials': 'true',
      'access-control-expose-headers': 'Content-Range',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '79',
      etag: 'W/"4f-lsLidoCOOiTyDVjYkFZzRb1La9s"',
      date: 'Tue, 13 Sep 2022 12:11:00 GMT',
      connection: 'close'
    },
    data: undefined,
    meta: undefined,
    errors: [ [Object] ]
  },
  errors: [ { message: 'Token expired.', extensions: [Object] } ]
}

```

**Comment by 53rg0** [comment]
But it works)

**Comment by azrikahar** [comment]
> When i replace i got

I believe those are just the `console.log` statements in the Auth store in your Nuxt project, if I'm not mistaken 🙂

> But! It works :)

Glad it works! Marking this as resolved for now 👍

**Comment by bryantgillespie** [comment]
Yes that's right, that's coming from the `console.log` within the Auth store because the token is expired. 
https://github.com/53rg0/directus-nuxt/blob/8a71f0d6b829202f6ab5016e246a166ddfd92199/store/auth.ts#L69-L83

But if you watch the requests you should see that the SDK is refreshing the token for you and then calling the `/users/me` endpoint again to get the data.

<img width="634" alt="ScreenShot 2022-09-13 at 08 37 09@2x" src="https://user-images.githubusercontent.com/23302570/189905817-9d7bf9bf-debd-4789-911b-d935fbbf05f2.png">
